### PR TITLE
Photo Stream for iPhoto

### PR DESCRIPTION
**Pull request by jjac**
Implementation of the Apple Photo Stream feature for iPhoto, specifically:
- Add apropriate node if usage of iPhoto 9.2.1 or higher is detected
- Parse plist for Photo Stream images and display
- prepare for future (third party) Photo Stream support of Aperture
- Include English and German localizations

Includes fixes for issues #32 and #39.

### CODE REVIEW

**Comment by mikeabdullah** [comment]
I've pulled into the main repo for further testing. Will merge after that.

**Comment by jjac** [comment]
Hi Terrence,

thanks for your thorough investigation. A couple of remarks:

The roundtrip you descibed one has to take to eventually see the photo stream if the feature was disabled in iPhoto is due to a current bug in iMedia (see issue #33). iMedia should get notified of any change in iPhoto and promptly reload its node tree so you should not have to restart iMedia to get to see your Photo Stream photos. Also, are you sure that you must quit iPhoto to make it rewrite its AlbumData.xml? On my system (OS X 10.7.2, iPhoto 9.2.1) it rewrites it almost instantaneously after a Photo Stream photo was added or a photo got deleted or similar changes occurred.

Nonetheless could it be helpful to know whether Photo Stream is currently turned on in iPhoto or not. I personally know of no way to tell. Even if you turn back off Photo Stream in iPhoto its AlbumData.xml will still claim there are Photo Stream photos currently present (in my case some subset of the photos iPhoto's Photo Stream held before). After I turned Photo Stream back on iPhoto showed two photos (the ones from the stream of this month) while its AlbumData.xml still held the aforementioned subset (including the ones from this month). Every new photo then streamed showed up in both applications.

BTW: iBooks Author doesn't yet incorporate Photo Stream into its media browser. It seems to me that Apple still has to smooth a couple of rough edges here.

> If we can't do that, then I think that if no photos are shown we should indicate to the user that they need to turn on Photo Stream in iPhoto. (So, in gray text where photos should be, some message to the user.) I really think we need UI to help people get started.

I like your idea although this would only be displayed if you never had iPhoto Photo Stream turned on before (given what I stated above). Unfortunately I don't have time to implement it myself.

Regarding issue #33: I just commented on its status and intend to submit a fix this week.

Regards, Jörg.

**Comment by jjac** [comment]
Hi Mike, have you had a chance to test this pull request yet?

Regards, Jörg.

**Comment by mikeabdullah** [comment]
Well Terrence has tested it for us :)
I think our concern remains that it's not as user-friendly as we'd like. I'm going to look at #33 first and come back to this.

**Pull request merged**
