### PR TITLE
Fix error handling

### PR DESCRIPTION
**Pull request by mikeabdullah**
It has come to my attention that iMedia's error handling is wrong and thus crash-prone. These commits address that. Can anyone spot anything I've missed?

### CODE REVIEW

**Comment by danielpunkass** [comment]
Mike, thanks for getting inspired to fix the error handling on a wider basis in the project. I am hopeful that this will end up addressing a small but consistent number of crashes I continue to see in iMedia.

I would probably change one thing, which is for the cases where you stripped the error handling entirely because there are no failure conditions. I would include in these methods a nil'ing of outError for two reasons:
1. In case there is some case in the error propagation that we're missing, where nil is still a safer bet than "random".
2. As an idiomatic reminder to future editors that in those parsers, any error that is derived in the method should be set directly on the outError variable.

If you're confident that the errors propagated from these methods can not escape the scope of everything you've fixed the logic for, then it's probably not a big deal. But I'd probably err on the side of caution in this one regard.

**Comment by mikeabdullah** [comment]
I'm strongly against nilling out error pointers:
1. That's introducing a new convention just for iMedia, outside of Cocoa's standard behaviour
2. It introduces more code, especially so when it has to be commented to note why we're going beyond Cocoa's regular approach

I do need to look through the code I've fixed to make sure there's no other code calling it and making a false assumption.

**Comment by danielpunkass** [comment]
I can get behind your rationale. I mainly suggested it in case the propagation chain is not fully auditable and you want to play it safe.

**Comment by mikeabdullah** [comment]
Well I have in fact just done an audit and I'm pretty happy. Those methods get called from little code that actually uses the error pointer in any way at present. In fact the biggest possible problem is the number of times I found bits of code not caring whether those method calls succeeded or not!

**Comment by danielpunkass** [comment]
Haha! By the way did you see my note on the mailing list about the zombie NSErrors? I couldn't figure out how to properly inject that into the pull request.

**Comment by mikeabdullah** [comment]
@danielpunkass yep, cherry-picking that is next on my list!

**Pull request merged**
