### PR TITLE
Use security-scoped bookmarks for custom folders

### PR DESCRIPTION
**Pull request by mikeabdullah**

### CODE REVIEW

**Comment by danwood** [comment]
Now that I understand the ivar use of the dispatch_once_t, I'm fine with this

**Comment by benuri** [comment]
In my app, or in any other document-based app that properly manages its URLs, there is indeed no problem except the leak.

However, other apps (probably like yours I guess, because you said that the rest of your app can't access resources that iMedia stopped access to them) will fail to reload resources that came from a custom parser that was removed.

Here is the scenario where your solution will fail:
1. Add a custom folder to iMedia tree
2. Open the custom folder in the thumbnails browser
3. Drag an item from the browser to use it in the rest of the app (where you said that it "didn't scale" with my solution)
4. Remove the folder from iMedia tree
5. Quit your app
6. Relaunch the app (the parser should not "start access now"
7. See the problem with your solution: the resource can't be loaded by your app because the parser that was supposed to "start access" to its parent folder was not loaded in this launch.

My point is that if my solution does not work, than it's a bug in the app, not in my solution, and your solution does not fully cover on this bug anyway.

**Comment by mikeabdullah** [comment]
Here's the flow that occurs in Sandvox under such a scenario:
1. Add a custom folder to iMedia tree
2. Open the custom folder in the thumbnails browser
3. Drag a photo from the browser to use it in the rest of the app
4. Remove the folder from iMedia tree
5. Quit your app. At this point or earlier, the document gets saved, copying the photo into the doc package
6. Relaunch the app (the parser should not "start access now")
7. The app loads the photo just fine because it's made its own copy

If iMedia were to cut off access to the custom folder at step 4 or sooner, saving the doc wouldn't be able to copy the photo; it would no longer have access to the file.

I really don't want to have to go through all pasteboard handling code to make it more suspicious of the pasteboard. It currently assumes that any files dragged in are added to the sandbox for the remainder of the process's lifetime (happens when dragging from outside the app). Seems weird and annoying to have to take a bunch of extra steps to handle drags from within the app.

**Comment by benuri** [comment]
I see.
But if you use the default NSUndoManager with Auto-Save enabled, the document would be probably autosaved right after step 3, and if it's not done automatically, you can force it so be autosaved after every drag operation. Right?

**Comment by mikeabdullah** [comment]
The autosave system is deliberately designed to kick in at what it can best deem to be unobtrusive moments. It most definitely does **not** autosave after every single undoable operation is registered. In practice, autosaves are deferred until the user switches to another app, pauses while working with the app, or reaches a time threshold where the system feels it really needs to get an autosave done.

Furthermore, saving is potentially an asynchronous process. We certainly have adopted async saving in Sandvox. So yes, an autosave could be triggered after a drop operation, but then would have to block the main thread while the save completed, or wait until a bit later before stopping access to the resource.

One bonus of the system's design of _not_ autosaving immediately is that if the drop was mistakenly of the wrong file, or in the wrong place, there is time for the user to hit undo or delete the file, _before_ the app wastes time copying it into the document.

Again, I have to ask, is there any practical benefit to your approach beyond avoiding a potential leak? It seems you want to go through a lot of effort which nobody else is advising, including Apple themselves.

**Comment by benuri** [comment]
The practical benefit of my approach is that it forces applications to behave correctly in the case I described above even in applications where the document does not create its own copy of the resource upon saving (I think that it's a reasonable to assume that documents are allowed to save a reference to resources outside iMedia rather than copying them).

I agree that the problem can be worked-around in several other ways, such as coping resources upon saving and save before quit, but such workarounds are app-specific and are not "the right way" to manage resources, just as you would not use a weak reference for resources that came from other modules in your app.

Also, Apple do ask that:
"**Warning**: You must balance every call to the startAccessingSecurityScopedResource method with a corresponding call to the stopAccessingSecurityScopedResource method. If you fail to relinquish your access when you no longer need a file-system resource, your app leaks kernel resources. If sufficient kernel resources are leaked, your app loses its ability to add file-system locations to its sandbox, such as via Powerbox or security-scoped bookmarks, until relaunched." (https://developer.apple.com/library/mac/#documentation/Cocoa/Reference/Foundation/Classes/NSURL_Class/Reference/Reference.html)

**Comment by mikeabdullah** [comment]
When writing a sandboxed app, the basic rules of resources to play by are:
1. When receiving a file from a pasteboard or open panel, you are granted access for the remainder of the process's lifetime
2. If access is required beyond that, you must either:
   - copy the file somewhere more permanently accessible
   - save a bookmark to it
3. If access is required between reboots of the Mac, a bookmark needs to be security-scoped

My version of the code makes iMedia's custom folders conform to that spec.

What you're proposing is that apps should instead play by a more restrictive version of rule 1, something like:
1. When receiving a file from a pasteboard or open panel, you are granted access, but with no guarantee as to how long for. You must call `-startAccessingSecurityScopedResource` to retain access beyond the immediate scope of your pasteboard handling code

It bothers me that this rule is now extra, rather tricky work to do. I don't believe any of Cocoa's built-in UI components take care to do this when receiving a drop or paste.

Furthermore, any media URLs received off the pasteboard are highly unlikely to actually be security-scoped themselves. Can you confirm that the call to `-startAccessingSecurityScopedResource` still succeeds when faced with this?

I am well aware of that Apple docs note on leaking kernel resources. Logically to me though, for a constrained resource, it's better to "leak" it only on occasions where custom folders are removed from iMedia, rather than to have potentially hundreds of `-startAccessingSecurityScopedResource` calls/sessions on the go.

**Comment by benuri** [comment]
My proposal is indeed more restrictive in terms of rule 1, but only for URLs that dragged from other parts of the apps, which are not part of Powerbox.
Your implementation indeed mimics Apple behavior by giving access permission to the resources recieved from iMedia for the lifetime of the app.

It also seems that Apple implementation for granting access via powerbox, uses the same pool of kernel resources as "start"/"stop" as they say that if you fail to call stop enough times the user will not be able to open files even via powerbox. So that's also a positive point in your approach.

Fortunately I could make my app works properly according to my approach.
I still think that my approach may be suitable to other apps, such as apps that use iMedia only to open documents, or apps that have only a few points or functions to open files.

I can confirm that a non-security-scoped URLs can be easily converted to security-scoped URLs by creating security-scoped bookmarks and resolves them.
But I believe that it is not needed and you can call `startAccessingSecurityScopedResources` on the non-security-scoped URLs as well.

To conclude, although your approach now makes sense to me, I still prefer my approach as it's not hard to make it works in my app, so I would love to have an option to call `stopAccessing...` in `didStopUsingParser`.
I now think that I can achieve this by creating one hooking point and subclassing, so I can make it by myself without changing iMedia too much.

Anyway, thanks for the interesting discussion!

**Comment by mikeabdullah** [comment]
I'd certainly be interested in using `-didStopUsingParser` as a mechanism for that; feel free to send in a pull request. My worry would be that iMedia itself isn't very strict at exactly balancing calls to `-willUseParser` and it though, so you'd likely end up leaking anyway :-(

Generating a security-scoped URL by that route concerns me ever-so-slightly, purely because it relies on the file system, introducing two new points which might fail and need to be handled appropriately. Worth noting that at present for example, you can't generate a security-scoped bookmark to an image in the Desktop Pictures folder.

**Pull request merged**
