### PR TITLE
Updated Framework header to be compatible with ARC

### PR DESCRIPTION
**Pull request by tonyxiao**
Updated IMBIconCache.h to be compatible with ARC
Updated Objective-Flickr project to the latest commit on github, which is compatible with ARC

### CODE REVIEW

**Comment by mikeabdullah** [comment]
Hi Tony,

There's an awful lot here! I'd very much appreciate it you split up into separate commits and pull requests. As far as I can see there's three things changing here:
- adjust the framework's headers so as not to conflict with ARC
- newer version of ObjectiveFlickr that compiles with ARC? Or is more compatible with it?
- tweak to .gitignore

**Comment by tonyxiao** [comment]
Hi Mike

There are two things here. The only file in iMedia that I have changed is the `IMBIconCache.h`. In particular, `__unsafe_unretained` has been added in front of a few variable declarations. 

```
 typedef struct _IMBIconTypeMappingEntry
 {
-  NSString* fIconType;
-  NSString* fApplicationIconName;
-  NSString* fFallbackIconName;
-  NSString* fAlternateIconName;
-  NSString* fAlternateBundlePath;
+  __unsafe_unretained NSString* fIconType;
+  __unsafe_unretained NSString* fApplicationIconName;
+  __unsafe_unretained NSString* fFallbackIconName;
+  __unsafe_unretained NSString* fAlternateIconName;
+  __unsafe_unretained NSString* fAlternateBundlePath;
 }
```

The other change is updating the ObjectiveFlickr framework to its [latest commit](https://github.com/lukhnos/objectiveflickr/commit/734c8ed568f825ab8006baec799005e1e6b50f17). It seems really massive but all I did was removing the `ObjectiveFlickr` directory inside `iMedia` and then cloned a new one from source in its place. `Objective-Flickr` itself is still under manual memory management, they just updated the publicly exposed headers so that those headers would compile from referencing projects that use ARC. Hope that explains a bit. Let me know if you still want me to split the commit into 2 or something.

**Comment by mikeabdullah** [comment]
Ah, good point, I see the .gitignore change is part of Objective-Flickr now.

**Comment by mikeabdullah** [comment]
Right, having looked at this further, since Objective-Flickr is now hosted in git, I'd far rather move to using a submodule than this checkin.

**Comment by tonyxiao** [comment]
Absolutely, I'd much rather use the submodule as well. I'll cancel the pull and wait for submodule update then :)

Tony

**Pull request merged**
