### PR TITLE
Fix for repeatedly oversubscribing to FSEvents on reload

### PR DESCRIPTION
**Pull request by danielpunkass**
Previously we were abusing FSEvents by re-registering for notification watched nodes on every reload. I noticed during testing with aggressive reloads that it was actually possible to fry the FSEvents system so that it stopped registering new events.

I added an assertion in addPath: in UKFSEventsWatcher, to ensure that in normal
usage no path is ever registered twice.

I added new helper methods in IMBLibraryController to centralize registration
and deregistration for FS events. Then I added a new call in -reload to
ensure that any existing event registrations for the nodes we are about to
reload get unregistered before reloading.

### CODE REVIEW

**Comment by mikeabdullah** [comment]
Seeing as this can't be automatically merged, would you mind merging `karelia:master` into your branch and handling the conflicts there?

**Comment by danielpunkass** [comment]
Hi Mike - this gets precisely to the problem we were chatting about in email, that I had to go back in time to find a branch-point that wouldn't include all those bogus duplicate commits in my repo. master on my fork is in fact up-to-date with karelia, and if I issue a pull request e.g. from master right now, it has all the bogus commits, but the diffs are the same as here for code.

So if you're willing to suck up the "muck" of those bogus duplicate commits, you should be able to just pull from danielpunkass/master to get precisely these changes merged more cleanly with your tree.

**Comment by danielpunkass** [comment]
Mike, I think I'll use this as an excuse to try out some git repository repair. :) I'm going to see if I can more or less repull karelia/iMedia into my repo and re-apply my changes to pull request back to you. Since I think you are the only repository pulling from mine so far, this should be a pretty safe move I think.

**Comment by danielpunkass** [comment]
Phew! OK, I was hesitant to just merge with karelia:master because I knew that going forward my master branch, and any new branches based on it, would always have this clutter in the pull requests. I realized though that what I could do is rename my master branch and then essentially rename a branch off this fix branch as the new master. So going forward I should be able to produce clean pull requests for you if don't get into the cherry-picking pickle again :)

**Comment by danielpunkass** [comment]
I haven't used NSCountedSet before, I'll take a look and try to get an updated patch here soon.

**Pull request merged**
